### ISSUE TITLE
Kick me out before i can download and install

### ISSUE THREAD

**Issue by OmegaB31** [SneezingCactus/gmmaker#4]
Once tampermonkey opens the screen freezes and then after it closes the tab.

**Comment by SneezingCactus** [comment]
GMMaker versions 1.0.0 and above are way too heavy for the normal install prompt, so you have to use an alternative install method as described in the [installation guide](https://sneezingcactus.github.io/gmmaker/docs/tutorials/GettingStarted-1.html).
